# Generated by Django 6.0.7 on 2026-07-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurants/')),
                ('address', models.CharField(max_length=300)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('delivery_time', models.CharField(blank=True, max_length=50)),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
    ]
